
name: pygbag_build
on: [workflow_dispatch]


jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            python -m pip install pygbag
            python -m pygbag --ume_block 1 --icon utils/icon.png --template utils/default.tmpl --no_opt --build $GITHUB_WORKSPACE/ecsRogue/main.py
    - name : "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: ecsRogue/build/web
